### ISSUE TITLE
ritland estimator >> 1

### ISSUE THREAD

**Issue by jgx65** [timothyfrasier/related#7]
I am getting Ritland estimator of relatedness much larger than 1:

```{r}
head(gdata[,1:11]
```
 X1.112 X1 X2 X3 X4 X5 X6 X7 X8 X9 X10
1      1  9  6 10  2  7  8  8  8  7   7
2      2  9  9 10  9  4  8  9  5  7   5
3      3  3 10  2  2  4  3  8  4  7   4
4      4 10 10  3  2  8  4  4  8  4  10
5      5 10  4  3  5  3  6  9  4  5   3
6      6  9  8  9  2  3  4  4  4  3    

```{r}
input<-readgenotypedata(gdata[,1:11])
output<-coancestry(input$gdata,wang=1,lynchli=1,lynchrd=1,ritland=1,quellergt = 1,dyadml=1)
head(output$relatedness$ritland)
```
[1] 508.1869 250.4386 392.6925  -0.2587 110.9465 793.3921

Any idea?

**Comment by jgx65** [comment]
Problem solved: alleles were read as factors.  After reading them as integers, things were resolved.

**Comment by timothyfrasier** [comment]
Hi Jerome:

Great, thanks. I was just about to take a look at it - it seemed very weird though, and I had not seen that problem before. Thanks for keeping me posted.

-Tim

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Timothy R. Frasier
Department of Biology & Forensic Sciences Program
Saint Mary's University
923 Robie Street
Halifax, NS B3H 3C3
Canada
Tel: (902) 491-6382
Fax: (902) 420-5046
E-mail: timothy.frasier@smu.ca<mailto:timothy.frasier@smu.ca>
www.frasierlab.ca<http://www.frasierlab.ca>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


On Aug 30, 2016, at 4:26 AM, Jerome Goudet <notifications@github.com<mailto:notifications@github.com>> wrote:


Problem solved: alleles were read as factors. After reading them as integers, things were resolved.
